import Navbar from "./components/Navbar"
import "./globals.css"

export const metadata = {
  title: "Steven's Blog",
  description: "Generated by Steven",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-slate-200">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
